import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Copy, 
  Check, 
  ChevronDown, 
  ExternalLink, 
  Music, 
  Camera, 
  Mic2, 
  Image as ImageIcon, 
  FileText, 
  CheckSquare,
  Package,
  Clock
} from 'lucide-react';
import { AssetForgeResult } from '../types';
import { cn } from '../lib/utils';

interface AssetForgeRendererProps {
  data: AssetForgeResult;
  isExample?: boolean;
}

export const AssetForgeRenderer = ({ data, isExample }: AssetForgeRendererProps) => {
  const [activeTab, setActiveTab] = useState<'script' | 'thumbnail' | 'voice' | 'footage' | 'music' | 'checklist'>('script');
  const [openSections, setOpenSections] = useState<Set<number>>(new Set([1, 2]));
  const [checkedItems, setCheckedItems] = useState<Set<number>>(new Set());
  const [isCopied, setIsCopied] = useState(false);

  // Production Timer Data
  const productionTasks = [
    { label: 'Thumbnail Architecture', time: '15m' },
    { label: 'Voiceover Recording', time: '20m' },
    { label: 'Asset Assembly', time: '45m' },
    { label: 'Neural Mix (Audio)', time: '10m' }
  ];

  const toggleSection = (id: number) => {
    const newSet = new Set(openSections);
    if (newSet.has(id)) newSet.delete(id);
    else newSet.add(id);
    setOpenSections(newSet);
  };

  const toggleCheck = (index: number) => {
    const newSet = new Set(checkedItems);
    if (newSet.has(index)) newSet.delete(index);
    else newSet.add(index);
    setCheckedItems(newSet);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  const exportFullPack = () => {
    const sectionsText = data.scriptOutline.map(s => 
      `Section ${s.section}: ${s.title} (${s.duration})\nPurpose: ${s.purpose}\nKey Points:\n${s.keyPoints.map(p => ` - ${p}`).join('\n')}\nTransition: ${s.transitionLine}`
    ).join('\n\n');

    const footageText = `Opening: ${data.stockFootage.openingShots.join(', ')}\n` + 
      data.stockFootage.sectionTerms.map(s => `Section ${s.section}: ${s.terms.join(', ')}`).join('\n');

    const packText = `═══════════════════════════════
VYREX ASSET FORGE — PRODUCTION PACK
${data.videoTitle}
═══════════════════════════════

SEO VARIANTS:
A: ${data.seoVariants[0] || ''}
B: ${data.seoVariants[1] || ''}
C: ${data.seoVariants[2] || ''}
D: ${data.seoVariants[3] || ''}

OPENING HOOK:
${data.openingHook}

SCRIPT OUTLINE:
${sectionsText}

THUMBNAIL BRIEF:
Text: ${data.thumbnailBrief.mainText} | Emotion: ${data.thumbnailBrief.emotion}
Layout: ${data.thumbnailBrief.layout}
Colors: ${data.thumbnailBrief.colorPalette.join(', ')}
Style: ${data.thumbnailBrief.referenceStyle}

VOICEOVER:
Voice: ${data.voiceoverGuide.recommendedVoice} | Speed: ${data.voiceoverGuide.speed}
Tone: ${data.voiceoverGuide.tone}
Emphasis: ${data.voiceoverGuide.emphasisWords.join(', ')}

FOOTAGE SEARCH TERMS:
${footageText}

MUSIC:
Intro: ${data.musicDirection.intro} | Build: ${data.musicDirection.build} | Outro: ${data.musicDirection.outro}

CHECKLIST:
${data.uploadChecklist.map((item, i) => `${checkedItems.has(i) ? '[X]' : '[ ]'} ${item}`).join('\n')}
═══════════════════════════════
Generated by VYREX Asset Forge`;

    navigator.clipboard.writeText(packText);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const tabs = [
    { id: 'script', label: 'SCRIPT', icon: FileText, emoji: '📋' },
    { id: 'thumbnail', label: 'THUMBNAIL', icon: ImageIcon, emoji: '🎬' },
    { id: 'voice', label: 'VOICE', icon: Mic2, emoji: '🎙' },
    { id: 'footage', label: 'FOOTAGE', icon: Camera, emoji: '📸' },
    { id: 'music', label: 'MUSIC', icon: Music, emoji: '🎵' },
    { id: 'checklist', label: 'CHECKLIST', icon: CheckSquare, emoji: '✅' },
  ];

  return (
    <div className="space-y-6 animate-fade-in relative">
      {/* PRODUCTION TIMER SPECIAL FEATURE */}
      <div className="bg-[#080b15] border border-vy-white/10 rounded-2xl p-4 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <Clock className="w-4 h-4 text-vy-accent animate-pulse" />
          <span className="font-mono text-[9px] text-vy-white uppercase font-black tracking-widest">⏱ PRODUCTION TIMER</span>
        </div>
        <div className="flex gap-6 overflow-x-auto pb-1 scrollbar-hide">
          {productionTasks.map((task, i) => (
            <div key={i} className="flex flex-col">
              <span className="font-mono text-[8px] text-vy-muted uppercase whitespace-nowrap">{task.label}</span>
              <span className="font-display font-black text-xs text-vy-white uppercase">{task.time}</span>
            </div>
          ))}
        </div>
        <div className="px-3 py-1 bg-vy-white/5 border border-vy-white/10 rounded font-mono text-[8px] text-vy-muted uppercase tracking-widest">
          EST: 1H 30M
        </div>
      </div>

      {/* Tab bar */}
      <div className="flex border border-vy-border rounded-xl overflow-hidden bg-vy-surface/50 p-1">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={cn(
              "flex-1 flex items-center justify-center gap-2 py-2.5 text-[10px] font-bold transition-all rounded-lg",
              activeTab === tab.id 
                ? "bg-vy-accent/10 border border-vy-accent/30 text-white shadow-[0_0_15px_rgba(232,84,42,0.1)]" 
                : "text-vy-muted hover:text-vy-white hover:bg-white/5"
            )}
          >
            <span className="text-xs">{tab.emoji}</span>
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="min-h-[400px]">
        {activeTab === 'script' && (
          <div className="space-y-6 animate-fade-up">
            <div className="flex items-center justify-between gap-4 p-6 bg-vy-surface border border-vy-border rounded-2xl">
              <h1 className="font-display font-black text-2xl text-vy-white leading-tight flex-1">{data.videoTitle}</h1>
              <button 
                onClick={() => copyToClipboard(data.videoTitle)}
                className="p-2.5 bg-white/5 hover:bg-vy-accent/20 border border-vy-border hover:border-vy-accent/50 rounded-xl transition-all group"
              >
                <Copy className="w-4 h-4 text-vy-muted group-hover:text-vy-accent" />
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {data.seoVariants.map((variant, i) => (
                <div key={i} className="bg-vy-surface/40 border border-vy-border rounded-xl p-4 flex flex-col gap-3 group relative overflow-hidden">
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-[9px] text-vy-accent font-black uppercase tracking-widest">VARIANT {String.fromCharCode(65 + i)}</span>
                    <button 
                      onClick={() => copyToClipboard(variant)}
                      className="p-1.5 opacity-0 group-hover:opacity-100 transition-opacity bg-white/5 border border-vy-border rounded-md"
                    >
                      <Copy className="w-3 h-3 text-vy-muted hover:text-vy-accent" />
                    </button>
                  </div>
                  <p className="font-display font-semibold text-sm text-vy-white leading-relaxed">{variant}</p>
                </div>
              ))}
            </div>

            <div className="p-6 bg-vy-accent/[0.03] border-l-4 border-vy-accent border-y border-r border-vy-border rounded-r-2xl relative group">
              <div className="font-mono text-[9px] text-vy-accent font-black uppercase tracking-widest mb-3 flex items-center gap-2">
                <span className="text-sm">⚡</span> OPENING HOOK
              </div>
              <p className="font-display font-medium text-lg italic text-[#c8dce8] leading-relaxed pr-10">
                "{data.openingHook}"
              </p>
              <button 
                onClick={() => copyToClipboard(data.openingHook)}
                className="absolute top-6 right-6 p-2 opacity-0 group-hover:opacity-100 transition-opacity bg-vy-accent/10 border border-vy-accent/30 rounded-lg"
              >
                <Copy className="w-4 h-4 text-vy-accent" />
              </button>
            </div>

            <div className="space-y-3">
              {data.scriptOutline.map((section) => (
                <div key={section.section} className="border border-vy-border rounded-xl overflow-hidden bg-vy-surface/20">
                  <button 
                    onClick={() => toggleSection(section.section)}
                    className="w-full px-5 py-4 flex items-center gap-4 hover:bg-white/5 transition-colors text-left"
                  >
                    <div className="w-6 h-6 rounded-full bg-vy-accent/20 border border-vy-accent/40 flex items-center justify-center font-mono text-[10px] text-vy-accent font-bold">
                      {section.section}
                    </div>
                    <span className="flex-1 font-display font-bold text-sm text-vy-white uppercase tracking-wide">{section.title}</span>
                    <div className="flex items-center gap-3">
                       <span className="px-2 py-0.5 bg-white/10 border border-white/10 rounded font-mono text-[9px] text-vy-muted">{section.duration}</span>
                       <ChevronDown className={cn("w-4 h-4 text-vy-muted transition-transform", openSections.has(section.section) && "rotate-180")} />
                    </div>
                  </button>
                  <AnimatePresence>
                    {openSections.has(section.section) && (
                      <motion.div
                        initial={{ height: 0 }}
                        animate={{ height: "auto" }}
                        exit={{ height: 0 }}
                        className="overflow-hidden bg-black/20"
                      >
                        <div className="p-5 pt-0 space-y-4 border-t border-vy-border/50">
                          <div className="mt-4 italic text-[11px] text-vy-muted leading-relaxed">
                            <span className="font-bold uppercase text-[9px] not-italic mr-2">Purpose:</span> {section.purpose}
                          </div>
                          <ul className="space-y-2">
                            {section.keyPoints.map((point, idx) => (
                              <li key={idx} className="flex gap-2 text-xs text-[#c8dce8] leading-relaxed">
                                <span className="text-vy-accent">→</span> {point}
                              </li>
                            ))}
                          </ul>
                          <div className="p-3 bg-vy-accent/5 border border-vy-accent/10 rounded-lg text-xs italic text-vy-accent">
                            {section.transitionLine}
                          </div>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              ))}
            </div>
          </div>
        )}

        {activeTab === 'thumbnail' && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 animate-fade-up">
            <div className="space-y-4">
              <div 
                className="relative w-full aspect-video rounded-3xl overflow-hidden border border-white/20 shadow-2xl"
                style={{
                  background: `linear-gradient(135deg, ${data.thumbnailBrief.colorPalette[0] || '#0a0a14'}, ${data.thumbnailBrief.colorPalette[1] || '#1a0814'}, ${data.thumbnailBrief.colorPalette[2] || '#0a0a14'})`
                }}
              >
                <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-20 pointer-events-none" />
                <div className="absolute inset-x-8 inset-y-0 flex flex-col justify-center">
                  <h2 className="font-black text-white leading-[0.9] drop-shadow-[0_4px_10px_rgba(0,0,0,0.5)] font-display" style={{ fontSize: 'clamp(24px, 5vw, 48px)' }}>
                    {data.thumbnailBrief.mainText.toUpperCase()}
                  </h2>
                </div>
                <div className="absolute bottom-6 left-6 px-3 py-1 bg-vy-accent text-white font-bold text-[10px] uppercase tracking-widest rounded shadow-lg">
                  {data.thumbnailBrief.emotion}
                </div>
                <div className="absolute top-6 right-6 px-2 py-1 bg-black/80 text-white font-mono text-[10px] rounded border border-white/10">
                  10:42
                </div>
              </div>
            </div>

            <div className="space-y-6">
              <div className="space-y-6 bg-vy-surface border border-vy-border p-8 rounded-3xl">
                <div className="space-y-2">
                  <label className="font-mono text-[9px] text-vy-accent font-black uppercase tracking-widest">Layout Direction</label>
                  <p className="text-sm font-medium text-[#c8dce8] leading-relaxed">{data.thumbnailBrief.layout}</p>
                </div>

                <div className="space-y-3">
                  <label className="font-mono text-[9px] text-vy-accent font-black uppercase tracking-widest block">Color Palette</label>
                  <div className="flex gap-3">
                    {data.thumbnailBrief.colorPalette.map((color, i) => (
                      <div key={i} className="flex flex-col items-center gap-2">
                        <div className="w-10 h-10 rounded-full border border-white/20 shadow-lg" style={{ backgroundColor: color }} />
                        <span className="font-mono text-[9px] text-vy-muted">{color}</span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="space-y-2">
                  <label className="font-mono text-[9px] text-vy-accent font-black uppercase tracking-widest">Visual Reference</label>
                  <div className="px-4 py-3 bg-white/5 border border-vy-border rounded-xl font-mono text-sm text-vy-white italic">
                    "{data.thumbnailBrief.referenceStyle}"
                  </div>
                </div>

                <button 
                  onClick={() => copyToClipboard(`Thumbnail Brief:\nText: ${data.thumbnailBrief.mainText}\nLayout: ${data.thumbnailBrief.layout}\nStyle: ${data.thumbnailBrief.referenceStyle}`)}
                  className="w-full py-4 bg-vy-surface2 border border-vy-border rounded-xl font-display font-black text-[10px] text-vy-white uppercase tracking-widest hover:border-vy-accent hover:text-vy-accent transition-all"
                >
                  COPY FULL BRIEF
                </button>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'voice' && (
          <div className="max-w-3xl mx-auto space-y-8 animate-fade-up">
            <div className="text-center space-y-2">
              <div className="font-mono text-[10px] text-vy-muted uppercase tracking-[0.3em]">Recommended ElevenLabs Voice</div>
              <h2 className="font-display font-black text-5xl text-vy-cyan tracking-tighter uppercase drop-shadow-[0_0_20px_rgba(0,200,255,0.2)]">
                {data.voiceoverGuide.recommendedVoice}
              </h2>
              <div className="inline-block px-3 py-1 bg-vy-cyan/10 border border-vy-cyan/30 text-vy-cyan text-[9px] font-bold rounded-full">
                STORYTELLER PRESET
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-vy-surface border border-vy-border p-6 rounded-2xl space-y-4">
                 <div className="flex justify-between items-center">
                    <label className="font-mono text-[9px] text-vy-accent font-black uppercase tracking-widest">Pace Mode</label>
                    <span className="text-2xl font-black text-vy-white font-display tracking-tight">{data.voiceoverGuide.speed}</span>
                 </div>
                 <div className="h-1 bg-white/5 rounded-full overflow-hidden">
                    <div className="h-full bg-vy-accent" style={{ width: `${(parseFloat(data.voiceoverGuide.speed) / 1.5) * 100}%` }} />
                 </div>
                 <p className="text-[10px] text-vy-muted italic leading-relaxed">
                   Slower delivery increases perceived authority and retention in history/educational niches.
                 </p>
              </div>

              <div className="bg-vy-surface border border-vy-border p-6 rounded-2xl relative overflow-hidden">
                 <label className="font-mono text-[9px] text-vy-accent font-black uppercase tracking-widest block mb-3">Tone Direction</label>
                 <p className="text-sm font-semibold text-vy-white leading-relaxed">{data.voiceoverGuide.tone}</p>
                 <div className="absolute top-0 right-0 w-16 h-16 bg-vy-accent/5 rounded-full -mr-8 -mt-8" />
              </div>
            </div>

            <div className="space-y-4">
              <label className="font-mono text-[9px] text-vy-muted font-black uppercase tracking-widest block text-center">Emphasis Words (Stress Points)</label>
              <div className="flex flex-wrap justify-center gap-3">
                {data.voiceoverGuide.emphasisWords.map((word, i) => (
                  <div key={i} className="px-4 py-2 bg-vy-accent/10 border border-vy-accent/30 rounded-xl font-display font-black text-sm text-vy-accent shadow-lg">
                    {word.toUpperCase()}
                  </div>
                ))}
              </div>
            </div>

            <div className="space-y-6 pt-4">
              <label className="font-mono text-[9px] text-vy-muted font-black uppercase tracking-widest block text-center">Emotional Delivery Arc</label>
              <div className="relative h-24 flex items-center">
                <div className="absolute left-0 right-0 h-[2px] bg-vy-border" />
                <div className="flex justify-between w-full relative z-10">
                  {data.voiceoverGuide.emotionalArc.split('→').map((stage, i) => (
                    <div key={i} className="flex flex-col items-center gap-3">
                      <div className={cn(
                        "w-4 h-4 rounded-full shadow-[0_0_10px_rgba(232,84,42,0.4)]",
                        i === 0 ? "bg-vy-white" : i === 1 ? "bg-vy-accent" : i === 2 ? "bg-vy-accent2" : "bg-vy-cyan"
                      )} />
                      <span className="font-mono text-[10px] text-vy-white font-bold uppercase tracking-widest">{stage.trim()}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'footage' && (
          <div className="space-y-8 animate-fade-up">
            <div className="space-y-4">
              <label className="font-mono text-[9px] text-vy-accent font-black uppercase tracking-widest">Opening Scene Search terms</label>
              <div className="flex flex-wrap gap-3">
                {data.stockFootage.openingShots.map((term, i) => (
                  <Chip key={i} text={term} color="cyan" />
                ))}
              </div>
            </div>

            <div className="space-y-4">
              <label className="font-mono text-[9px] text-vy-accent font-black uppercase tracking-widest">Section-specific Visuals</label>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {data.stockFootage.sectionTerms.map((section) => (
                  <div key={section.section} className="bg-vy-surface border border-vy-border p-5 rounded-2xl flex flex-col gap-4">
                    <div className="flex items-center gap-3">
                       <div className="w-5 h-5 rounded-md bg-vy-accent/20 flex items-center justify-center font-mono text-[9px] text-vy-accent font-black border border-vy-accent/20">{section.section}</div>
                       <span className="font-mono text-[9px] text-vy-muted uppercase font-black">Section Terms</span>
                    </div>
                    <div className="flex flex-wrap gap-2">
                       {section.terms.map((term, i) => (
                         <Chip key={i} text={term} color="white" />
                       ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="bg-vy-accent/[0.03] border border-vy-accent/20 p-6 rounded-2xl relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                   <Camera className="w-12 h-12 text-vy-accent" />
                </div>
                <label className="font-mono text-[9px] text-vy-accent font-black uppercase tracking-widest block mb-3">Visual Aesthetic Direction</label>
                <p className="text-sm font-semibold text-[#c8dce8] leading-relaxed italic pr-12">
                   "{data.stockFootage.styleGuide}"
                </p>
              </div>

              <div className="bg-red-500/5 border border-red-500/10 p-6 rounded-2xl">
                 <label className="font-mono text-[9px] text-red-500 font-black uppercase tracking-widest block mb-3">Avoid These visuals</label>
                 <div className="flex flex-wrap gap-2">
                    {data.stockFootage.avoidTerms.map((term, i) => (
                      <div key={i} className="flex items-center gap-2 px-3 py-1.5 bg-red-500/10 border border-red-500/20 rounded-lg font-mono text-[9px] text-red-400 uppercase font-black">
                         <span>✗</span> {term}
                      </div>
                    ))}
                 </div>
              </div>
            </div>

            <div className="flex items-center justify-center gap-4 py-4">
               {[
                 { name: 'PEXELS', url: 'https://www.pexels.com' },
                 { name: 'PIXABAY', url: 'https://pixabay.com' },
                 { name: 'STORYBLOCKS', url: 'https://www.storyblocks.com' }
               ].map((site) => (
                 <a 
                   key={site.name}
                   href={site.url}
                   target="_blank"
                   rel="noopener noreferrer"
                   className="flex items-center gap-2 px-4 py-2 border border-vy-border rounded-lg text-xs font-bold text-vy-muted hover:text-white hover:border-white/20 transition-all uppercase"
                 >
                   {site.name} <ExternalLink className="w-3 h-3" />
                 </a>
               ))}
            </div>
          </div>
        )}

        {activeTab === 'music' && (
          <div className="max-w-xl mx-auto space-y-6 animate-fade-up">
            {[
              { label: 'INTRO', val: data.musicDirection.intro, color: 'border-vy-cyan text-vy-cyan' },
              { label: 'BUILD', val: data.musicDirection.build, color: 'border-vy-accent text-vy-accent' },
              { label: 'OUTRO', val: data.musicDirection.outro, color: 'border-vy-green text-vy-green' }
            ].map((m) => (
              <div key={m.label} className={cn("bg-vy-surface border border-vy-border p-6 rounded-2xl border-l-4", m.color)}>
                <label className={cn("font-mono text-[9px] font-black uppercase tracking-[0.2em] block mb-2 opacity-70")}>{m.label} MUSIC MOOD</label>
                <p className="text-sm font-semibold text-vy-white leading-relaxed">{m.val}</p>
              </div>
            ))}

            <div className="pt-6 space-y-3">
               <label className="font-mono text-[9px] text-red-500 font-black uppercase tracking-widest block text-center">Avoid These Genres</label>
               <div className="flex flex-wrap justify-center gap-2">
                  {data.musicDirection.avoidGenres.map((term, i) => (
                    <div key={i} className="px-3 py-1.5 bg-red-500/10 border border-red-500/20 rounded-lg font-mono text-[9px] text-red-400 uppercase font-black uppercase">
                       {term}
                    </div>
                  ))}
               </div>
            </div>
          </div>
        )}

        {activeTab === 'checklist' && (
          <div className="max-w-xl mx-auto space-y-10 animate-fade-up">
            <div className="space-y-3">
              <div className="flex justify-between items-end">
                <span className="font-mono text-[10px] text-vy-white font-bold uppercase tracking-widest">Production Progress</span>
                <span className="font-mono text-[10px] text-vy-accent font-black">
                  {Math.round((checkedItems.size / data.uploadChecklist.length) * 100)}%
                </span>
              </div>
              <div className="h-2 bg-white/5 rounded-full overflow-hidden">
                <motion.div 
                   initial={{ width: 0 }}
                   animate={{ width: `${(checkedItems.size / data.uploadChecklist.length) * 100}%` }}
                   className={cn(
                     "h-full transition-colors duration-500",
                     checkedItems.size === data.uploadChecklist.length ? "bg-[#22d3a0] shadow-[0_0_15px_rgba(34,211,160,0.5)]" : "bg-vy-accent"
                   )}
                />
              </div>
              {checkedItems.size === data.uploadChecklist.length && (
                 <motion.div 
                   initial={{ opacity: 0, y: 10 }}
                   animate={{ opacity: 1, y: 0 }}
                   className="text-center font-display font-black text-[11px] text-[#22d3a0] uppercase tracking-[0.3em] pt-2"
                 >
                   READY TO UPLOAD 🚀
                 </motion.div>
              )}
            </div>

            <div className="space-y-4">
              {data.uploadChecklist.map((item, i) => (
                <div 
                  key={i} 
                  className={cn(
                    "flex items-center gap-4 p-5 bg-vy-surface border border-vy-border rounded-2xl cursor-pointer transition-all",
                    checkedItems.has(i) ? "opacity-50 grayscale border-vy-accent/20" : "hover:border-vy-accent/40"
                  )}
                  onClick={() => toggleCheck(i)}
                >
                  <div className={cn(
                    "w-6 h-6 rounded-lg border-2 flex items-center justify-center transition-all",
                    checkedItems.has(i) ? "bg-vy-accent border-vy-accent shadow-[0_0_10px_rgba(232,84,42,0.4)]" : "border-vy-border bg-black/20"
                  )}>
                    {checkedItems.has(i) && <Check className="w-4 h-4 text-white" />}
                  </div>
                  <span className={cn(
                    "font-display font-bold text-sm text-[#c8dce8] transition-all",
                    checkedItems.has(i) && "line-through text-vy-muted"
                  )}>
                    {item}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      <div className="pt-8 border-t border-vy-border">
        <button 
          onClick={exportFullPack}
          className={cn(
            "w-full py-5 flex items-center justify-center gap-3 bg-gradient-to-r from-vy-violet to-[#4c1d95] text-white rounded-2xl font-display font-black text-xs uppercase tracking-[0.3em] hover:shadow-[0_0_30px_rgba(139,92,246,0.3)] transition-all relative group overflow-hidden shadow-lg hover:scale-[1.01] active:scale-[0.99]",
            isCopied && "from-vy-green to-[#059669] hover:shadow-[0_0_30px_rgba(34,211,160,0.3)]"
          )}
        >
          <div className="relative z-10 flex items-center gap-2">
            {isCopied ? (
              <>
                <Check className="w-4 h-4" />
                COPIED TO CLIPBOARD
              </>
            ) : (
              <>
                📦 EXPORT FULL PRODUCTION PACK
              </>
            )}
          </div>
          <div className="absolute inset-0 bg-white/10 translate-y-full group-hover:translate-y-0 transition-transform origin-bottom" />
        </button>
      </div>
    </div>
  );
};

const Chip = ({ text, color }: { text: string, color: 'cyan' | 'white' | 'orange' }) => {
  const [copied, setCopied] = useState(false);

  const handleClick = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button 
      onClick={handleClick}
      className={cn(
        "flex items-center gap-2 px-3 py-1.5 rounded-lg font-mono text-[9px] uppercase font-black border transition-all active:scale-95",
        color === 'cyan' ? "bg-vy-cyan/5 border-vy-cyan/20 text-vy-cyan hover:bg-vy-cyan/10" :
        color === 'orange' ? "bg-vy-accent/5 border-vy-accent/20 text-vy-accent hover:bg-vy-accent/10" :
        "bg-white/5 border-white/10 text-vy-muted hover:border-white/20 hover:text-white"
      )}
    >
      {copied ? <Check className="w-3 h-3" /> : text}
      {copied && <span className="lowercase text-[8px] font-normal tracking-normal opacity-60">copied</span>}
    </button>
  );
};
